export type Kind={id:string;name:string;type:'tráva'|'oheň'|'voda'|'normální'|'hmyz'|'kámen';color:number;baseHp:number;attack:number;speed:number;evolves?:string;evolveAt?:number};
export const species:Record<string,Kind>={
 bulbasaur:{id:'bulbasaur',name:'Bulbasaur',type:'tráva',color:0x64b86c,baseHp:22,attack:7,speed:6,evolves:'ivysaur',evolveAt:8},ivysaur:{id:'ivysaur',name:'Ivysaur',type:'tráva',color:0x4fa779,baseHp:30,attack:10,speed:8},
 charmander:{id:'charmander',name:'Charmander',type:'oheň',color:0xf08a45,baseHp:20,attack:8,speed:8,evolves:'charmeleon',evolveAt:8},charmeleon:{id:'charmeleon',name:'Charmeleon',type:'oheň',color:0xd95a47,baseHp:28,attack:11,speed:10},
 squirtle:{id:'squirtle',name:'Squirtle',type:'voda',color:0x59a6d8,baseHp:24,attack:7,speed:6,evolves:'wartortle',evolveAt:8},wartortle:{id:'wartortle',name:'Wartortle',type:'voda',color:0x558dc9,baseHp:32,attack:10,speed:8},
 pidgey:{id:'pidgey',name:'Pidgey',type:'normální',color:0xc9a56b,baseHp:18,attack:6,speed:8},rattata:{id:'rattata',name:'Rattata',type:'normální',color:0xa378ad,baseHp:17,attack:7,speed:9},caterpie:{id:'caterpie',name:'Caterpie',type:'hmyz',color:0x75ba45,baseHp:19,attack:5,speed:5},weedle:{id:'weedle',name:'Weedle',type:'hmyz',color:0xc4a33d,baseHp:18,attack:6,speed:6},oddish:{id:'oddish',name:'Oddish',type:'tráva',color:0x4f6fae,baseHp:21,attack:6,speed:5},geodude:{id:'geodude',name:'Geodude',type:'kámen',color:0x8a8175,baseHp:28,attack:9,speed:3}
};
export const moveByType={tráva:'Listový úder',oheň:'Plamínek',voda:'Vodní proud',normální:'Náraz',hmyz:'Bodnutí',kámen:'Kamenomet'} as const;
export const effectiveness:Record<string,Record<string,number>>={tráva:{voda:2,kámen:2,oheň:.5,hmyz:.5},oheň:{tráva:2,hmyz:2,voda:.5,kámen:.5},voda:{oheň:2,kámen:2,tráva:.5},kámen:{oheň:2,hmyz:2},hmyz:{tráva:2,oheň:.5},normální:{kámen:.5}};
export const dialogues={professor:['Vítej v Lipovém městě!','Vyber si partnera a vydej se na cestu.'],nurse:['Tví Pokémoni jsou zase plní sil!'],leader:['Jsem Robin, vůdce skalního stadionu.','Ukaž mi, co ses cestou naučil!'],win:['Výborně! Získáváš LISTOVÝ ODZNAK!','První kapitola je dokončena. Gratuluji!']};
