create extension if not exists pgcrypto;
create type public.device_status as enum ('online','offline');
create type public.execution_status as enum ('queued','running','success','failed');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, email text, display_name text, created_at timestamptz not null default now());
create table public.devices (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, name text not null, platform text not null, hostname text not null, agent_version text not null, status public.device_status not null default 'offline', credential_hash text, last_seen_at timestamptz, created_at timestamptz not null default now());
create table public.automations (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, device_id uuid not null references public.devices(id) on delete cascade, name text not null, description text not null default '', enabled boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.automation_triggers (id uuid primary key default gen_random_uuid(), automation_id uuid not null unique references public.automations(id) on delete cascade, type text not null check(type in ('file_created')), config jsonb not null default '{}');
create table public.automation_conditions (id uuid primary key default gen_random_uuid(), automation_id uuid not null references public.automations(id) on delete cascade, type text not null check(type in ('file_extension')), position integer not null default 0 check(position >= 0), config jsonb not null default '{}', unique(automation_id, position));
create table public.automation_actions (id uuid primary key default gen_random_uuid(), automation_id uuid not null references public.automations(id) on delete cascade, type text not null check(type in ('move_file','copy_file','rename_file')), position integer not null default 0 check(position >= 0), config jsonb not null default '{}', unique(automation_id, position));
create table public.executions (id uuid primary key default gen_random_uuid(), automation_id uuid not null references public.automations(id) on delete cascade, device_id uuid not null references public.devices(id) on delete cascade, status public.execution_status not null default 'queued', trigger_payload jsonb not null default '{}', started_at timestamptz not null default now(), finished_at timestamptz, error_message text);
create table public.execution_logs (id uuid primary key default gen_random_uuid(), execution_id uuid not null references public.executions(id) on delete cascade, level text not null check(level in ('info','warning','error')), message text not null, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table public.device_pairing_tokens (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, token_hash text not null unique, expires_at timestamptz not null, used_at timestamptz, created_at timestamptz not null default now());

create index devices_user_id_idx on public.devices(user_id); create index automations_user_device_idx on public.automations(user_id,device_id); create index executions_device_started_idx on public.executions(device_id,started_at desc); create index executions_automation_idx on public.executions(automation_id); create index execution_logs_execution_idx on public.execution_logs(execution_id,created_at); create index pairing_expiry_idx on public.device_pairing_tokens(expires_at) where used_at is null;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,email) values(new.id,new.email); return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security; alter table public.devices enable row level security; alter table public.automations enable row level security; alter table public.automation_triggers enable row level security; alter table public.automation_conditions enable row level security; alter table public.automation_actions enable row level security; alter table public.executions enable row level security; alter table public.execution_logs enable row level security; alter table public.device_pairing_tokens enable row level security;
create policy profiles_owner on public.profiles for all using(id=auth.uid()) with check(id=auth.uid());
create policy devices_owner on public.devices for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy automations_owner on public.automations for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy triggers_owner on public.automation_triggers for all using(exists(select 1 from public.automations a where a.id=automation_id and a.user_id=auth.uid())) with check(exists(select 1 from public.automations a where a.id=automation_id and a.user_id=auth.uid()));
create policy conditions_owner on public.automation_conditions for all using(exists(select 1 from public.automations a where a.id=automation_id and a.user_id=auth.uid())) with check(exists(select 1 from public.automations a where a.id=automation_id and a.user_id=auth.uid()));
create policy actions_owner on public.automation_actions for all using(exists(select 1 from public.automations a where a.id=automation_id and a.user_id=auth.uid())) with check(exists(select 1 from public.automations a where a.id=automation_id and a.user_id=auth.uid()));
create policy executions_owner on public.executions for select using(exists(select 1 from public.automations a where a.id=automation_id and a.user_id=auth.uid()));
create policy logs_owner on public.execution_logs for select using(exists(select 1 from public.executions e join public.automations a on a.id=e.automation_id where e.id=execution_id and a.user_id=auth.uid()));
create policy pairing_owner on public.device_pairing_tokens for all using(user_id=auth.uid()) with check(user_id=auth.uid());

create or replace function public.consume_pairing_token(p_hash text,p_name text,p_platform text,p_hostname text,p_version text,p_credential_hash text) returns uuid language plpgsql security definer set search_path=public as $$ declare token public.device_pairing_tokens; device uuid; begin select * into token from public.device_pairing_tokens where token_hash=p_hash and used_at is null and expires_at>now() for update; if not found then raise exception 'Invalid or expired pairing code'; end if; update public.device_pairing_tokens set used_at=now() where id=token.id; insert into public.devices(user_id,name,platform,hostname,agent_version,credential_hash,status,last_seen_at) values(token.user_id,p_name,p_platform,p_hostname,p_version,p_credential_hash,'online',now()) returning id into device; return device; end $$;
revoke all on function public.consume_pairing_token(text,text,text,text,text,text) from public,anon,authenticated;
